### ISSUE TITLE
.progressbar.sh[26]: 0403-057 Syntax error at line 26 : `=~' is not expected.

### ISSUE THREAD

**Issue by imv7** [adriano-pinaffo/progressbar.sh#1]
:/home/scripts/tests > ./progressbar.sh 12
./progressbar.sh[26]: 0403-057 Syntax error at line 26 : `=~' is not expected.

**Comment by adriano-pinaffo** [comment]
Weird, I had not seen this.... were you using bash (3 years ago)? :D
